lang: ru-RU
encoding: utf-8
url: https://ntmrk.github.io
permalink: pretty
highlighter: rouge
markdown: kramdown

sass:
  style: :compressed

gems:
  - jekyll-paginate

paginate: 10
paginate_path: "/:num"
